/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as ProfileRouteImport } from './../../pages/profile'
import { Route as InvoicesRouteImport } from './../../pages/invoices'
import { Route as ContractsRouteImport } from './../../pages/contracts'
import { Route as ConsumptionRouteImport } from './../../pages/consumption'
import { Route as IndexRouteImport } from './../../pages/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionRoute = ConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consumption': typeof ConsumptionRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consumption': typeof ConsumptionRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consumption': typeof ConsumptionRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consumption' | '/contracts' | '/invoices' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consumption' | '/contracts' | '/invoices' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/consumption'
    | '/contracts'
    | '/invoices'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsumptionRoute: typeof ConsumptionRoute
  ContractsRoute: typeof ContractsRoute
  InvoicesRoute: typeof InvoicesRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumption': {
      id: '/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof ConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsumptionRoute: ConsumptionRoute,
  ContractsRoute: ContractsRoute,
  InvoicesRoute: InvoicesRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
